name: transfer_manager_flutter
description: Zero-configuration Flutter facade for transfer_manager on Android and iOS.
version: 2.1.2
homepage: https://github.com/pinzarulab/transfer_manager
repository: https://github.com/pinzarulab/transfer_manager
issue_tracker: https://github.com/pinzarulab/transfer_manager/issues
topics:
  - download
  - upload
  - background
  - notifications
  - workmanager

environment:
  sdk: ^3.8.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.6
  transfer_manager: ^2.1.0
  transfer_manager_android: ^2.1.1
  transfer_manager_ios: ^2.1.1
  transfer_manager_platform_interface: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
