name: transfer_manager
description: A protocol-aware, crash-safe transfer engine for Dart and Flutter.
version: 1.0.0
homepage: https://github.com/pinzarulab/transfer_manager

environment:
  sdk: ^3.8.0

dependencies:
  crypto: ^3.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
