name: transfer_manager_android
description: Android WorkManager implementation for transfer_manager.
version: 2.0.1
homepage: https://github.com/pinzarulab/transfer_manager
repository: https://github.com/pinzarulab/transfer_manager
issue_tracker: https://github.com/pinzarulab/transfer_manager/issues

environment:
  sdk: ^3.8.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  transfer_manager: ^2.0.1
  transfer_manager_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pinzarulab.transfer_manager_android
        pluginClass: TransferManagerAndroidPlugin
